# Site settings
title: MerkaLabs
description: Exceptionally good at ApplicationMerka :)
keywords: MerkaLabs, ApplicationMerka, Cool
author: MerkaLabs
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
